apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatapp-backend.fullname" . }}-env
data:
  DB_HOST: {{ .Values.cm.DB_HOST | quote }}
  DB_PORT: {{ .Values.cm.DB_PORT | default "3306" | quote }}
  DB_NAME: {{ .Values.cm.DB_NAME | default "chatapp_db" | quote }}
  DB_USER: {{ .Values.cm.DB_USER | default "chatapp_user" | quote }}