apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp-backend.fullname" . }}-svc
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "chatapp-backend.selectorLabels"  . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}

