apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s" (include "my.fullname" .)) .Values.cm.name }}-configmap
data:
  MYSQL_USER: {{ .Values.cm.user | default "chatapp_user" | quote }}
  MYSQL_DATABASE: {{ .Values.cm.database | default "chatapp_db" | quote }}
