apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s" (include "my.fullname" .)) .Values.secret.name }}-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote}}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | quote}}
