apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ default (printf "%s" (include "my.fullname" .)) .Values.cm.name }}-sts
spec:
  selector:
    matchLabels:
      {{- include "my.selectorLabels"  . | nindent 6 }}
  serviceName: {{ default (printf "%s" (include "my.fullname" .)) .Values.service.name }}-headless
  replicas: {{ .Values.sts.replicas | default 1 }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        {{- include "my.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 40
      containers:
        - name: {{ default (printf "%s" (include "my.fullname" .)) .Values.cm.name }}-container
          image: {{ .Values.sts.image.repository }}:{{ .Values.sts.image.tag }}
          imagePullPolicy: {{ .Values.sts.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port.targetPortNo }}
              name: {{ .Values.port.targetPortName }}

          {{- if .Values.sts.livenessProbe.present }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port.targetPortName }}
            initialDelaySeconds: {{ .Values.sts.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sts.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.sts.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.sts.livenessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.sts.readinessProbe.present }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port.targetPortName }}
            initialDelaySeconds: {{ .Values.sts.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sts.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.sts.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.sts.readinessProbe.failureThreshold }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ default (printf "%s" (include "my.fullname" .)) .Values.cm.name }}-configmap
            - secretRef:
                name: {{ default (printf "%s" (include "my.fullname" .)) .Values.secret.name }}-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 200Mi
