apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- include "mychart.labels" . | nindent 2 }}
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: "{{ .Values.favorite.food }}"
  {{- if eq .Values.favorite.food "pizza" }}
  dessert: "ice cream"
  {{ else }}
  dessert: "cake"
  {{- end -}}
