apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp-frontend.fullname" . }}-svc
spec:
  type: NodePort
  selector:
    {{ include "chatapp-frontend.selectorLabels" . }}
  ports:
    - port: {{ .Values.svc.port | default 80 }}
      targetPort: {{ .Values.svc.targetPort | default 80 }}
      nodePort: {{ .Values.svc.nodePort | default 30080 }}
